# Generated by Django 4.0.3 on 2022-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting_places', '0001_initial'),
        ('player', '0002_player_member_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='common_hunts',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='hunting_places.huntingground'),
        ),
    ]
