# Generated by Django 4.0.3 on 2022-03-13 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exiva',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=35)),
                ('distance', models.CharField(choices=[('F', 'Far'), ('VF', 'Very-Far'), ('N', ' ')], max_length=2)),
                ('direction', models.CharField(choices=[('N', 'North'), ('W', 'West'), ('E', 'East'), ('S', 'South'), ('NW', 'North-West'), ('NE', 'North-East'), ('SE', 'South-East'), ('SW', 'South-West')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuntingGround',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuntingExiva',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(help_text='0 is highest priority')),
                ('exiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_exiva', to='hunting_places.exiva')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_exiva', to='hunting_places.huntingground')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
