# Generated by Django 4.0.3 on 2022-03-07 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlist',
            name='guild',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='guild_tracker.guild'),
            preserve_default=False,
        ),
    ]
