# Generated by Django 4.0.3 on 2022-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('guild_tracker', '0002_playerlist_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='lists', to='player.player'),
        ),
    ]
