# Generated by Django 4.0.3 on 2022-03-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_tracker', '0003_alter_playerlist_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlist',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
