# Generated by Django 4.0.3 on 2022-03-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_tracker', '0004_playerlist_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='0 is highest priority'),
        ),
        migrations.AlterUniqueTogether(
            name='playerlist',
            unique_together={('guild', 'priority')},
        ),
    ]
